### ISSUE TITLE
[BE] ER 다이어그램 작성

### ISSUE THREAD

**Issue by sanhee** [isaac56/todo-list#22]
- 요구사항에 맞는 ERD 작성

**Comment by sanhee** [comment]
ERD `ver 1.0`

https://github.com/isaac56/todo-list/blob/dev/BE/Doc/ERD.png

## 회의록

1. 최신 순 정렬에 대한 기준❓
   - 날짜? 카드가 놓인 순서?
   - 요구사항에 날짜 관련 사항이 보이지 않아, `카드의 순서 기준`으로 결정
2. 드래그&드롭으로 카드를 다른 카드 뭉치 사이에 넣는 경우
   - https://stackoverflow.com/questions/14446859/what-does-the-pos-actually-mean-in-the-trello-api 참고
   - 넣으려는 사이드 요소의 평균값의 위치로 카드 Position 지정
   -  ex) B: 10: C: 12 A: 16 에서 C를 A와 B로 옮기려면? (A+B)/2 = 13  ➡ B:10 C:13 A:16 

3. (2)에 대한 문제점 : 언젠가는 자료형 MAX 범위에 도달해 스택오버플로우가 뜰 것이다.
   - 해결방안
      - double 사용 ✔
      - 리밸런싱
        - 나중에 생각

4.  History를 문자열로 저장을 해둘지? int로 저장을 할지?
   - 문자열은 연산이 유연하지 못하다?
   - int 인 경우 DB만을 보고 파악하기 어렵다.
     - 인덱스 테이블 비슷한 것을 만들자  EX) `Column Type`

**Comment by sanhee** [comment]
@isaac56  검토좀요!

**Comment by isaac56** [comment]
깔끔한 것 같습니다 ㅎㅎ 정리할 생각을 못했네요 고생하셨어요!
